version: '3.1'

services:
  springboot:
    build: ./back-end
    restart: always
    container_name: springboot
    ports:
      - 8000:8000
    working_dir: /opt/app
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: springboot-mongo
    environment:
      - MONGODB_DATABASE=fipe
    volumes:
      - $HOME/data/springboot-mongo-data:/data/db
      - $HOME/data/springboot-mongo-bkp:/data/bkp
    restart: always
    ports:
      - 27017:27017

  webserver:
    restart: unless-stopped
    build: ./front-end
    ports:
      - 8001:8001
    container_name: webserver
    image: nginx:stable
    tty: true
    volumes:
      - ./front-end/dist/prova-front/:/var/www
      - ./front-end/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - springboot

volumes:
  dbdata:
    driver: local
